
insert into cities  (name, country) values ('Wakefield', 'New Zealand');
insert into cities  (name, country) values ('Bristol', 'United Kingdom');
insert into cities  (name, country) values ('Lynchburg', 'United States');
insert into cities  (name, country) values ('San Antonio', 'United States');
insert into cities  (name, country) values ('Lawrenceville', 'United States');
insert into cities  (name, country) values ('New York City', 'United States');
insert into cities  (name, country) values ('Lakeland', 'United States');
insert into cities  (name, country) values ('Palmerston North', 'New Zealand');
insert into cities  (name, country) values ('Wiri', 'New Zealand');
insert into cities  (name, country) values ('Adelaide Mail Centre', 'Australia');
insert into cities  (name, country) values ('Birmingham', 'United States');
insert into cities  (name, country) values ('Honolulu', 'United States');
insert into cities  (name, country) values ('Tulsa', 'United States');
insert into cities  (name, country) values ('East End', 'United Kingdom');
insert into cities  (name, country) values ('El Paso', 'United States');
insert into cities  (name, country) values ('Portland', 'United States');
insert into cities  (name, country) values ('Kingsport', 'United States');
insert into cities  (name, country) values ('Kawerau', 'New Zealand');
insert into cities  (name, country) values ('Columbus', 'United States');
insert into cities  (name, country) values ('Charlotte', 'United States');
insert into cities  (name, country) values ('Kansas City', 'Australia');
insert into cities  (name, country) values ('Laurel', 'United States');
insert into cities  (name, country) values ('Wiri', 'Australia');
insert into cities  (name, country) values ('Newbiggin', 'United Kingdom');
insert into cities  (name, country) values ('Rockford', 'United States');
insert into cities  (name, country) values ('Sheffield', 'United Kingdom');
insert into cities  (name, country) values ('Linton', 'United Kingdom');
insert into cities  (name, country) values ('Washington', 'United States');
insert into cities  (name, country) values ('East End', 'New Zealand');
insert into cities  (name, country) values ('Wakefield', 'United States');
insert into cities  (name, country) values ('Evansville', 'United States');
insert into cities  (name, country) values ('Lancaster', 'United States');
insert into cities  (name, country) values ('Adelaide Mail Centre', 'United Kingdom');
insert into cities  (name, country) values ('Rockford', 'Australia');
insert into cities  (name, country) values ('Kansas City', 'United States');
insert into cities  (name, country) values ('Linton', 'Australia');
insert into cities  (name, country) values ('Charlton', 'United Kingdom');
insert into cities  (name, country) values ('Lynchburg', 'Australia');
insert into cities  (name, country) values ('Charlton', 'New Zealand');
insert into cities  (name, country) values ('Inglewood', 'United States');
insert into cities  (name, country) values ('Lancaster', 'New Zealand');
insert into cities  (name, country) values ('Houston', 'United States');
