
INSERT INTO cities(name,country) VALUES ('Wakefield','New Zealand');
INSERT INTO cities(name,country) VALUES ('Bristol','United Kingdom');
INSERT INTO cities(name,country) VALUES ('Lynchburg','United States');
INSERT INTO cities(name,country) VALUES ('San Antonio','United States');
INSERT INTO cities(name,country) VALUES ('Lawrenceville','United States');
INSERT INTO cities(name,country) VALUES ('New York City','United States');
INSERT INTO cities(name,country) VALUES ('Lakeland','United States');
INSERT INTO cities(name,country) VALUES ('Palmerston North','New Zealand');
INSERT INTO cities(name,country) VALUES ('Wiri','New Zealand');
INSERT INTO cities(name,country) VALUES ('Adelaide Mail Centre','Australia');
INSERT INTO cities(name,country) VALUES ('Birmingham','United States');
INSERT INTO cities(name,country) VALUES ('Honolulu','United States');
INSERT INTO cities(name,country) VALUES ('Tulsa','United States');
INSERT INTO cities(name,country) VALUES ('East End','United Kingdom');
INSERT INTO cities(name,country) VALUES ('El Paso','United States');
INSERT INTO cities(name,country) VALUES ('Portland','United States');
INSERT INTO cities(name,country) VALUES ('Kingsport','United States');
INSERT INTO cities(name,country) VALUES ('Kawerau','New Zealand');
INSERT INTO cities(name,country) VALUES ('Columbus','United States');
INSERT INTO cities(name,country) VALUES ('Charlotte','United States');
INSERT INTO cities(name,country) VALUES ('Kansas City','Australia');
INSERT INTO cities(name,country) VALUES ('Laurel','United States');
INSERT INTO cities(name,country) VALUES ('Wiri','Australia');
INSERT INTO cities(name,country) VALUES ('Newbiggin','United Kingdom');
INSERT INTO cities(name,country) VALUES ('Rockford','United States');
INSERT INTO cities(name,country) VALUES ('Sheffield','United Kingdom');
INSERT INTO cities(name,country) VALUES ('Linton','United Kingdom');
INSERT INTO cities(name,country) VALUES ('Washington','United States');
INSERT INTO cities(name,country) VALUES ('East End','New Zealand');
INSERT INTO cities(name,country) VALUES ('Wakefield','United States');
INSERT INTO cities(name,country) VALUES ('Evansville','United States');
INSERT INTO cities(name,country) VALUES ('Lancaster','United States');
INSERT INTO cities(name,country) VALUES ('Adelaide Mail Centre','United Kingdom');
INSERT INTO cities(name,country) VALUES ('Rockford','Australia');
INSERT INTO cities(name,country) VALUES ('Kansas City','United States');
INSERT INTO cities(name,country) VALUES ('Linton','Australia');
INSERT INTO cities(name,country) VALUES ('Charlton','United Kingdom');
INSERT INTO cities(name,country) VALUES ('Lynchburg','Australia');
INSERT INTO cities(name,country) VALUES ('Charlton','New Zealand');
INSERT INTO cities(name,country) VALUES ('Inglewood','United States');
INSERT INTO cities(name,country) VALUES ('Lancaster','New Zealand');
INSERT INTO cities(name,country) VALUES ('Houston','United States');