INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('cdeftiec1','3 Schlimgen Point','Bristol',69.49,'United Kingdom');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('rsproul6t','1 School Parkway','Lynchburg',151.22,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('gtullochcy','11953 Sachs Parkway','San Antonio',93.11,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('jtreneard7','92458 Declaration Center','Lawrenceville',191.63,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('mabbotsonck','26 Corscot Junction','New York City',168.24,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('eclampe6','1 Arkansas Plaza','Lakeland',95.23,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('cskeathbj','8592 Northview Road','Palmerston North',66.74,'New Zealand');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('mrembrandt4x','7 Clove Point','Wiri',137.55,'New Zealand');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('tdemico8f','3245 Fordem Terrace','Adelaide Mail Centre',83.96,'Australia');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('ssuerzaj','4440 Hansons Avenue','Birmingham',119.53,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('dsturgis4k','41256 Brickson Park Junction','Honolulu',182.21,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('rsiggensb0','3 Elka Avenue','Tulsa',127.52,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('rcarrabot59','66271 Summerview Terrace','East End',195.12,'United Kingdom');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('mmackessockcr','790 Thompson Center','El Paso',175.63,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('swilbud9x','77252 Westerfield Road','Portland',101.09,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('jpennettaa7','98595 Grayhawk Park','Kingsport',80.90,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('gpenton7p','1 Brentwood Terrace','Kawerau',59.80,'New Zealand');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('sheisler2a','3027 Hollow Ridge Circle','Columbus',145.28,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('rklicherdc','05 Carpenter Avenue','Charlotte',168.85,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('rwoolston4l','7 Hooker Point','Kansas City',109.89,'Australia');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('vrupke3f','16277 Roxbury Circle','Laurel',75.15,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('ncopoda','1769 Norway Maple Park','Wiri',179.59,'Australia');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('dkundt5n','7 Blackbird Park','Newbiggin',136.56,'United Kingdom');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('jromagosads','26057 Russell Junction','Rockford',158.88,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('socahsedy6f','56 Dovetail Plaza','Sheffield',164.19,'United Kingdom');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('smerriton5a','11 Grayhawk Lane','Linton',68.42,'United Kingdom');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('edilnot2m','9 Forest Place','Washington',162.56,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('cwayte6e','099 Melody Junction','East End',130.55,'New Zealand');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('rsuccamore9','678 Thackeray Pass','Wakefield',120.60,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('udollbr','39619 Kipling Road','Evansville',123.94,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('awifflercf','4 Eagan Hill','Lancaster',116.85,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('dstourton7l','08465 School Terrace','Adelaide Mail Centre',89.69,'United Kingdom');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('ckellington74','54711 Di Loreto Court','Rockford',140.43,'Australia');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('sarstingall1u','877 Clyde Gallagher Street','Kansas City',67.76,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('ksans3u','6 Reinke Hill','Linton',125.35,'Australia');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('cblampey9n','316 Forest Crossing','Charlton',91.74,'United Kingdom');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('lcrang0','990 Reindahl Park','Lynchburg',54.56,'Australia');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('vpochin8g','72 Eggendart Plaza','Charlton',191.56,'New Zealand');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('ncroke53','351 Warner Way','Inglewood',135.49,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('jbandtd3','7668 Atwood Circle','Lancaster',82.08,'New Zealand');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('bpachtav','4852 Park Meadow Park','Houston',186.29,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('bdomes','807 Crest Line Court','Wakefield',137.59,'New Zealand');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('ohainsworth4h','7904 Menomonie Hill','Bristol',137.12,'United Kingdom');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('yralestone14','9392 Park Meadow Center','Lynchburg',170.06,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('aickoviczas','1 Sullivan Junction','San Antonio',151.68,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('jpoland2b','85 New Castle Lane','Lawrenceville',164.44,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('cnicklenq','0 Declaration Plaza','New York City',119.06,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('pfilonb5','4 Farmco Park','Lakeland',73.48,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('ufarnsworth2j','964 Atwood Junction','Palmerston North',106.38,'New Zealand');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('flohdeh','9 Straubel Court','Wiri',127.56,'New Zealand');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('fforcadebc','235 Kedzie Plaza','Adelaide Mail Centre',57.64,'Australia');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('acrinage2t','7 Springs Way','Birmingham',142.52,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('bneillyj','094 Schiller Pass','Honolulu',80.34,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('calibone2r','403 Gateway Trail','Tulsa',176.07,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('dhiggoei','18 Eagle Crest Hill','East End',66.61,'United Kingdom');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('gfontellbk','88560 Golf View Terrace','El Paso',189.56,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('grossant82','55 Lakewood Trail','Portland',77.73,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('swinkless5r','29124 Scott Center','Kingsport',150.41,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('sgallelli75','48005 Chive Point','Kawerau',77.06,'New Zealand');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('jeyersap','9881 Buena Vista Park','Columbus',191.63,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('adorsay2g','52 Novick Parkway','Charlotte',78.06,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('edenyukhin6d','743 Di Loreto Road','Kansas City',134.95,'Australia');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('sdurnoc5','4 Burning Wood Hill','Laurel',175.33,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('jmacknockercw','306 Magdeline Lane','Wiri',96.66,'Australia');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('lbugden2f','648 Duke Point','Newbiggin',136.23,'United Kingdom');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('oberzonse','707 Texas Way','Rockford',181.71,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('ebedbury9c','37 Schurz Parkway','Sheffield',160.59,'United Kingdom');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('amcblain4','398 Mendota Trail','Linton',167.49,'United Kingdom');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('cmuzzinicl','34 Sunnyside Park','Washington',176.78,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('scrisall7v','67 Fremont Parkway','East End',107.66,'New Zealand');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('jcombesai','06 Laurel Way','Wakefield',181.52,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('mchoppend8','57 Kennedy Junction','Evansville',126.67,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('vhazeldine48','36459 Linden Plaza','Lancaster',190.97,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('dbrysony','6666 Westridge Street','Adelaide Mail Centre',197.33,'United Kingdom');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('mmacgianyao','4221 High Crossing Point','Rockford',117.96,'Australia');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('ksumpterad','9177 Pawling Circle','Kansas City',123.73,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('gmattes7u','28 Lunder Plaza','Linton',104.98,'Australia');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('epauling4z','6942 Lawn Place','Charlton',174.22,'United Kingdom');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('lbartelet4f','803 Schurz Court','Lynchburg',167.80,'Australia');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('nburlingham1b','116 Kropf Avenue','Charlton',147.28,'New Zealand');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('chanbury89','4223 American Ash Avenue','Inglewood',188.57,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('ndutson3e','17 Barnett Terrace','Lancaster',153.54,'New Zealand');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('ebrentnall9s','9 Kedzie Avenue','Houston',76.88,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('jhammerich9q','15874 Melby Court','Wakefield',148.23,'New Zealand');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('hchastaingal','839 Kropf Trail','Bristol',73.83,'United Kingdom');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('kmoulster26','17 Mosinee Road','Lynchburg',129.69,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('fhearsey7f','982 Artisan Terrace','San Antonio',173.25,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('rmackilpatrick3i','30948 Kingsford Center','Lawrenceville',164.38,'United States');
INSERT INTO place(host_id,address,city_id,price_per_night,country_id) VALUES ('fkenway5k','9 Goodland Avenue','New York City',159.16,'United States');

