insert into place  (host_id, address, city_id, country_id, price_per_night) values ('host_id', '980 Farragut Trail', 'Wakefield', 'New Zealand', 175.37);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('cdeftiec1', '3 Schlimgen Point', 'Bristol', 'United Kingdom', 69.49);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('rsproul6t', '1 School Parkway', 'Lynchburg', 'United States', 151.22);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('gtullochcy', '11953 Sachs Parkway', 'San Antonio', 'United States', 93.11);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('jtreneard7', '92458 Declaration Center', 'Lawrenceville', 'United States', 191.63);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('mabbotsonck', '26 Corscot Junction', 'New York City', 'United States', 168.24);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('eclampe6', '1 Arkansas Plaza', 'Lakeland', 'United States', 95.23);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('cskeathbj', '8592 Northview Road', 'Palmerston North', 'New Zealand', 66.74);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('mrembrandt4x', '7 Clove Point', 'Wiri', 'New Zealand', 137.55);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('tdemico8f', '3245 Fordem Terrace', 'Adelaide Mail Centre', 'Australia', 83.96);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('ssuerzaj', '4440 Hansons Avenue', 'Birmingham', 'United States', 119.53);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('dsturgis4k', '41256 Brickson Park Junction', 'Honolulu', 'United States', 182.21);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('rsiggensb0', '3 Elka Avenue', 'Tulsa', 'United States', 127.52);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('rcarrabot59', '66271 Summerview Terrace', 'East End', 'United Kingdom', 195.12);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('mmackessockcr', '790 Thompson Center', 'El Paso', 'United States', 175.63);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('swilbud9x', '77252 Westerfield Road', 'Portland', 'United States', 101.09);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('jpennettaa7', '98595 Grayhawk Park', 'Kingsport', 'United States', 80.9);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('gpenton7p', '1 Brentwood Terrace', 'Kawerau', 'New Zealand', 59.8);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('sheisler2a', '3027 Hollow Ridge Circle', 'Columbus', 'United States', 145.28);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('rklicherdc', '05 Carpenter Avenue', 'Charlotte', 'United States', 168.85);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('rwoolston4l', '7 Hooker Point', 'Kansas City', 'Australia', 109.89);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('vrupke3f', '16277 Roxbury Circle', 'Laurel', 'United States', 75.15);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('ncopoda', '1769 Norway Maple Park', 'Wiri', 'Australia', 179.59);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('dkundt5n', '7 Blackbird Park', 'Newbiggin', 'United Kingdom', 136.56);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('jromagosads', '26057 Russell Junction', 'Rockford', 'United States', 158.88);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('socahsedy6f', '56 Dovetail Plaza', 'Sheffield', 'United Kingdom', 164.19);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('smerriton5a', '11 Grayhawk Lane', 'Linton', 'United Kingdom', 68.42);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('edilnot2m', '9 Forest Place', 'Washington', 'United States', 162.56);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('cwayte6e', '099 Melody Junction', 'East End', 'New Zealand', 130.55);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('rsuccamore9', '678 Thackeray Pass', 'Wakefield', 'United States', 120.6);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('udollbr', '39619 Kipling Road', 'Evansville', 'United States', 123.94);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('awifflercf', '4 Eagan Hill', 'Lancaster', 'United States', 116.85);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('dstourton7l', '08465 School Terrace', 'Adelaide Mail Centre', 'United Kingdom', 89.69);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('ckellington74', '54711 Di Loreto Court', 'Rockford', 'Australia', 140.43);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('sarstingall1u', '877 Clyde Gallagher Street', 'Kansas City', 'United States', 67.76);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('ksans3u', '6 Reinke Hill', 'Linton', 'Australia', 125.35);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('cblampey9n', '316 Forest Crossing', 'Charlton', 'United Kingdom', 91.74);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('lcrang0', '990 Reindahl Park', 'Lynchburg', 'Australia', 54.56);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('vpochin8g', '72 Eggendart Plaza', 'Charlton', 'New Zealand', 191.56);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('ncroke53', '351 Warner Way', 'Inglewood', 'United States', 135.49);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('jbandtd3', '7668 Atwood Circle', 'Lancaster', 'New Zealand', 82.08);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('bpachtav', '4852 Park Meadow Park', 'Houston', 'United States', 186.29);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('bdomes', '807 Crest Line Court', 'Wakefield', 'New Zealand', 137.59);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('ohainsworth4h', '7904 Menomonie Hill', 'Bristol', 'United Kingdom', 137.12);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('yralestone14', '9392 Park Meadow Center', 'Lynchburg', 'United States', 170.06);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('aickoviczas', '1 Sullivan Junction', 'San Antonio', 'United States', 151.68);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('jpoland2b', '85 New Castle Lane', 'Lawrenceville', 'United States', 164.44);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('cnicklenq', '0 Declaration Plaza', 'New York City', 'United States', 119.06);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('pfilonb5', '4 Farmco Park', 'Lakeland', 'United States', 73.48);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('ufarnsworth2j', '964 Atwood Junction', 'Palmerston North', 'New Zealand', 106.38);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('flohdeh', '9 Straubel Court', 'Wiri', 'New Zealand', 127.56);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('fforcadebc', '235 Kedzie Plaza', 'Adelaide Mail Centre', 'Australia', 57.64);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('acrinage2t', '7 Springs Way', 'Birmingham', 'United States', 142.52);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('bneillyj', '094 Schiller Pass', 'Honolulu', 'United States', 80.34);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('calibone2r', '403 Gateway Trail', 'Tulsa', 'United States', 176.07);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('dhiggoei', '18 Eagle Crest Hill', 'East End', 'United Kingdom', 66.61);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('gfontellbk', '88560 Golf View Terrace', 'El Paso', 'United States', 189.56);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('grossant82', '55 Lakewood Trail', 'Portland', 'United States', 77.73);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('swinkless5r', '29124 Scott Center', 'Kingsport', 'United States', 150.41);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('sgallelli75', '48005 Chive Point', 'Kawerau', 'New Zealand', 77.06);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('jeyersap', '9881 Buena Vista Park', 'Columbus', 'United States', 191.63);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('adorsay2g', '52 Novick Parkway', 'Charlotte', 'United States', 78.06);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('edenyukhin6d', '743 Di Loreto Road', 'Kansas City', 'Australia', 134.95);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('sdurnoc5', '4 Burning Wood Hill', 'Laurel', 'United States', 175.33);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('jmacknockercw', '306 Magdeline Lane', 'Wiri', 'Australia', 96.66);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('lbugden2f', '648 Duke Point', 'Newbiggin', 'United Kingdom', 136.23);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('oberzonse', '707 Texas Way', 'Rockford', 'United States', 181.71);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('ebedbury9c', '37 Schurz Parkway', 'Sheffield', 'United Kingdom', 160.59);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('amcblain4', '398 Mendota Trail', 'Linton', 'United Kingdom', 167.49);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('cmuzzinicl', '34 Sunnyside Park', 'Washington', 'United States', 176.78);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('scrisall7v', '67 Fremont Parkway', 'East End', 'New Zealand', 107.66);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('jcombesai', '06 Laurel Way', 'Wakefield', 'United States', 181.52);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('mchoppend8', '57 Kennedy Junction', 'Evansville', 'United States', 126.67);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('vhazeldine48', '36459 Linden Plaza', 'Lancaster', 'United States', 190.97);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('dbrysony', '6666 Westridge Street', 'Adelaide Mail Centre', 'United Kingdom', 197.33);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('mmacgianyao', '4221 High Crossing Point', 'Rockford', 'Australia', 117.96);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('ksumpterad', '9177 Pawling Circle', 'Kansas City', 'United States', 123.73);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('gmattes7u', '28 Lunder Plaza', 'Linton', 'Australia', 104.98);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('epauling4z', '6942 Lawn Place', 'Charlton', 'United Kingdom', 174.22);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('lbartelet4f', '803 Schurz Court', 'Lynchburg', 'Australia', 167.8);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('nburlingham1b', '116 Kropf Avenue', 'Charlton', 'New Zealand', 147.28);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('chanbury89', '4223 American Ash Avenue', 'Inglewood', 'United States', 188.57);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('ndutson3e', '17 Barnett Terrace', 'Lancaster', 'New Zealand', 153.54);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('ebrentnall9s', '9 Kedzie Avenue', 'Houston', 'United States', 76.88);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('jhammerich9q', '15874 Melby Court', 'Wakefield', 'New Zealand', 148.23);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('hchastaingal', '839 Kropf Trail', 'Bristol', 'United Kingdom', 73.83);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('kmoulster26', '17 Mosinee Road', 'Lynchburg', 'United States', 129.69);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('fhearsey7f', '982 Artisan Terrace', 'San Antonio', 'United States', 173.25);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('rmackilpatrick3i', '30948 Kingsford Center', 'Lawrenceville', 'United States', 164.38);
insert into place  (host_id, address, city_id, country_id, price_per_night) values ('fkenway5k', '9 Goodland Avenue', 'New York City', 'United States', 159.16);
